file_format: "1"
id: corne_xiao
name: Corne XIO
type: shield
url: https://github.com/foostan/crkbd/
requires: [seeed_xiao]
features:
  - keys
siblings:
  #- corne_xiao_left
  #- corne_xiao_right
  - corne_xiao_dongle